### ISSUE TITLE
check_log3.pl - Build new RPM and EXE file

### ISSUE THREAD

**Issue by sastorsl** [pmcaulay/nagios-plugins#10]
@pmcaulay would be creat if you built a new EXE and new RPM packages for check_log3.pl

**Comment by pmcaulay** [comment]
I will as soon as I have some time, promise!

**Comment by sastorsl** [comment]
Guess you are close to finishing this issue with https://github.com/pmcaulay/nagios-plugins/commit/20386220e183e52f762f260df998a47a5a8791a9

I'm not depending on the EXE file, but is that in the loop as well?

**Comment by pmcaulay** [comment]
The RPMs are up to date; version 3.14 is a bugfix for Windows only and I've just uploaded a new EXE for that.
