### ISSUE TITLE
check_log3.exe for log files on remote SMB shares

### ISSUE THREAD

**Issue by master135** [pmcaulay/nagios-plugins#13]
Hi,

Probably this is not even an issue, but there is simply no such functions that I'm trying to get from check_log3.exe. Anyway.
We want to use check_log3 for monitoring of certain events in logs located on remote windows SMB file share.
Here is the scenario:
1. Server1 is monitored with nagios agent and has check_log3 in place
2. Logs for Server1 are located on SMB file share on Server2. Let's say \\Server2\Log\Log.txt
3. Server2 is not under our responsibility and we cannot monitor it with Nagios or do any changes for log location.

I've added string below to nsclient.ini
`check_log_onServer2=C:\Program Files\NSClient++\check_log3\check_log3.exe -l \\server2\Log\Log.txt -p 554501 -c 1`
As result I get this **Cannot read '\server2loglog.txt'**

Nsclient client service is running under system account, so acting from server1 security context. Everyone group has permissions to read log file on remote smb share. So this does not look to be security issue.
I've tried specifying nonexistent server name i.e. \\server3\log\log3.txt as path for a log file, but getting the same error message: Cannot read...

However if I run string below from command prompt on server1 it executes fine and I'm getting correct results
`C:\Program Files\NSClient++\check_log3\check_log3.exe -l \\server2\Log\Log.txt -p 554501 -c 1`

Maybe path to SMB share need to be specified in some specific format...
Well, dunno what to think here, need your help!

**Comment by pmcaulay** [comment]
Hi,

I'm not 100% sure but I think the LocalSystem account has no network privileges so it wouldn't be able to connect to remote file shares.  I think you're better off running NSClient++ on server2 directly.

Kind regards,
Peter

**Comment by pmcaulay** [comment]
An alternative is to run NSClient++ under a normal user identity, one with file share access rights on server2.

**Comment by master135** [comment]
Yes you are right. Usually it works with permissions for computer account (this is how LocalSystem account impersonalized in domain) or everyone group.
So I just tested and it worked fine. So closing this issue and thank you for your help!
