### ISSUE TITLE
sudo permissions

### ISSUE THREAD

**Issue by agit05** [pmcaulay/nagios-plugins#14]
Hello,

I have an issue running the script on the systems where log files (eg. /var/log/messages) is restricted to root only (perm. 400).
I know that in the past I was solving this by giving sudo rights to the icinga user, then in the script command appending "sudo" to the command that was requiring higher privileges.
Is this possible within this script? I do not find a command that is used to parse the logs, it is perhaps "=cut" on line 476 ?
Please advise.
Thank you.

**Comment by pmcaulay** [comment]
Hi,

Yes, the plugin work just fine with sudo.  (The "=cut" indicates the end of the POD manual section.  It's not a shell script.)

Kind regards,
Peter

**Comment by agit05** [comment]
Hi Peter,

Sorry, but it is not working with the sudo rights.
I have even tested with ALL permissions for the icinga user:
```
# Icinga2
Defaults:icinga  !requiretty
icinga ALL=(ALL) NOPASSWD: ALL
```

Still on log files with permission, like:
-rw------- 1 root root 124347 Apr 23 13:33 /var/log/messages

I get permission denied, which is normal.
I will try to use a wrap script to call the /usr/lib64/nagios/plugins/check_log3.pl with sudo.
Otherwise, I suppose the check_log3.pl should be changed to make it's calls with sudo.

Thanks.

**Comment by pmcaulay** [comment]
Hi,

The plugins does not make calls, it exclusively uses native Perl functions (otherwise it would not work on Windows, etc).  How do you run the plugin?

Kind regards,
Peter

**Comment by agit05** [comment]
Hi Peter,
I solved it with a wrap bash script, as I needed it to run on Linux hosts.
Thanks for the quick reaction.
