### ISSUE TITLE
Seek file is not created

### ISSUE THREAD

**Issue by PitoneMaledetto** [pmcaulay/nagios-plugins#15]
Hi,
thank you for this great plugin!
I have tried to use the -s switch to specify a seek file but it seems that this option does not work. It is ok for specifying the directory of the seek file but not the file itself.
When the file is specified it will instead revert to the default base name one.
I am using the plugin under Linux Debian.
Thank you.

**Comment by pmcaulay** [comment]
Hi,

That's odd, I cannot reproduce that.  What version of the plugin are you using?  Can you please send me the output of your command run with the --debug option?

Thanks!
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
we are running 3.13.

DEBUG output:
myserver:/srv/giuseppe/log# /usr/lib/nagios/plugins/check_log3.pl -i -m 'mylog.%d-%m-%Y.log' -l '/srv/giuseppe/log/' -P '/etc/nagios/check_logfiles.d/mylog_critical' -s '/tmp/giuseppe.seek' -c 1 --show-filename --missing=UNKNOWN --missing-msg='Log file not found' --no-perfdata --debug
debug: check_log3.pl version 3.13 starting
debug: warning=1, critical=1
debug: plugin timeout set to 15 seconds
debug: using line buffer: 0 back, 0 ahead
debug: using pattern file '/etc/nagios/check_logfiles.d/mylog_critical'
debug: looking for 'Giuseppe was lost'
debug: overriding seek file for dynamic filenames
debug: enabling timestamp substitutions
debug: looking for files matching '/srv/giuseppe/log/mylog.30-05-2018.log'
debug: only one matching file
debug: using log file '/srv/giuseppe/log/mylog.30-05-2018.log'
debug: using seek file '/tmp/srv-giuseppe-log-mylog.30-05-2018.log.seek'
debug: seek from 224984320 (eof = 224984320)
debug: reading file...
debug: found 0 maches, total lines 0, parse count 0, limits: warn 1 crit 1
debug: end result: 0
OK: Found 0 lines (limit=1/1): No matches found. [/srv/giuseppe/log/mylog.30-05-2018.log]

Thanks
Giuseppe

**Comment by pmcaulay** [comment]
Hi,

OK, I see.  When you use the -m option, the -s option will be ignored unless it points to either a directory or to the null device (/dev/null).  This is why you see "debug: overriding seek file for dynamic filenames" up there.

The reason is that seek files are specific to a particular log file, sharing a seek file among multiple files is not a good idea.  If the log rotates and the new file is read by the plugin, normally the file size will be less than the previous seek position, so the plugin knows the seek position is not valid and starts reading the new log file from the beginning.  However, this is not guaranteed: if the log rotates and the new file grows to the same or larger size than the previous log file between checks, the plugin does not detect that the files are not the same as before and would skip to the old seek position in the new file, which is incorrect.

My solution was simply to enforce log and seek filename correspondence if the filenames are not known in advance.  It lacks flexibility, but I haven't thought of a better way so far.  If you have, please share :)

Kind regards,
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
I am not sure if I have explained myself enough.
We are not trying to share the same seek file for multiple log files but we using check_log3.pl to have more than one type of check on the same log file.
By example, one check is for log age and another check is for errors.
So in Nagios we can set-up different log errors check for the same application.

That is why we require different seek files for the same log file that has a different (dated) log name every day as it is rotated.
Hope it helps.
Thank you.
Giuseppe

**Comment by pmcaulay** [comment]
Hi,

OK, I understand now.  Indeed, that is a valid use case and maybe the plugin is being too conservative.  Can you please pull the latest version of the plugin (3.15b) and add the -S option to your command?  This will force the -s option to work even though -m is in effect.

It's not the default because while mylog.%d-%m-%Y.log may match mylog.30-05-2018.log today, tomorrow it will match mylog.01-06-2018.log and yet the seek file remains the same; if e.g. checks do not run 24x7 and/or every 5 minutes it's possible for tomorrow's log file to be bigger than today's.  The plugin won't notice and you may miss alerts.  Only you can decide whether that's actually a problem.

Kind regards,
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
The plugin is still not using a specified seek file with the below commands.

The critical seek file will also need to be rotated, each day like the log file but using the -m glob option also creates a directory structured file


rolbapp:~# /usr/lib/nagios/plugins/check_log3.pl -i -m 'mylog.%d-%m-%Y.log' -l '/tmp/logs/' -P '/tmp/mylog_critical' -S '/tmp/mylog_critical.%d-%m-%Y.seek' -c 1 --show-filename --missing=UNKNOWN --missing-msg='Log file not found' --no-perfdata --debug
debug: check_log3.pl version 3.15b starting
debug: warning=1, critical=1
debug: plugin timeout set to 15 seconds
debug: using line buffer: 0 back, 0 ahead
debug: using pattern file '/tmp/mylog_critical'
debug: looking for 'Critical Error'
debug: enabling timestamp substitutions
debug: looking for files matching '/tmp/logs/mylog.05-06-2018.log'
debug: only one matching file
debug: using log file '/tmp/logs/mylog.05-06-2018.log'
debug: using auto seek file '/tmp/tmp-logs-mylog.05-06-2018.log.seek'
debug: previous seek position 107052410 (eof = 107052410)
debug: reading file from position 107052410
debug: found 0 maches, total lines 0, parse count 0, limits: warn 1 crit 1
debug: end result: 0
OK: Found 0 lines (limit=1/1): No matches found. [/tmp/logs/mylog.05-06-2018.log]


and with the -m gives the below

rolbapp:~# /usr/lib/nagios/plugins/check_log3.pl -i -m 'mylog.%d-%m-%Y.log' -l '/tmp/logs/' -P '/tmp/mylog_critical' -S -m '/tmp/mylog_critical.%d-%m-%Y.seek' -c 1 --show-filename --missing=UNKNOWN --missing-msg='Log file not found' --no-perfdata --debug
debug: check_log3.pl version 3.15b starting
debug: warning=1, critical=1
debug: plugin timeout set to 15 seconds
debug: using line buffer: 0 back, 0 ahead
debug: using pattern file '/tmp/mylog_critical'
debug: looking for 'Critical Error'
debug: enabling timestamp substitutions
debug: looking for files matching '/tmp/logs//tmp/mylog_critical.05-06-2018.seek'
debug: no matching files found, trying just '/tmp/logs/'
debug: using log file '/tmp/logs/'
Log file not found


Without the .%d-%m-%Y on the seek file it will still ignore the -S option

rolbapp:~# /usr/lib/nagios/plugins/check_log3.pl -i -m 'mylog.%d-%m-%Y.log' -l '/tmp/logs/' -P '/tmp/mylog_critical' -S '/tmp/mylog_critical.seek' -c 1 --show-filename --missing=UNKNOWN --missing-msg='Log file not found' --no-perfdata --debug
debug: check_log3.pl version 3.15b starting
debug: warning=1, critical=1
debug: plugin timeout set to 15 seconds
debug: using line buffer: 0 back, 0 ahead
debug: using pattern file '/tmp/mylog_critical'
debug: looking for 'Critical Error'
debug: enabling timestamp substitutions
debug: looking for files matching '/tmp/logs/mylog.05-06-2018.log'
debug: only one matching file
debug: using log file '/tmp/logs/mylog.05-06-2018.log'
debug: using auto seek file '/tmp/tmp-logs-mylog.05-06-2018.log.seek'
debug: previous seek position 107052410 (eof = 107052410)
debug: reading file from position 107052410
debug: found 0 maches, total lines 0, parse count 0, limits: warn 1 crit 1
debug: end result: 0
OK: Found 0 lines (limit=1/1): No matches found. [/tmp/logs/mylog.05-06-2018.log]

Thank you for your time.

**Comment by pmcaulay** [comment]
Hi,

The -S option does not take parameters, it's a flag.  (Hence "using auto seek file")  The timestamp macros that -m uses don't work with seek files.

I guess the real problem is that without -S, the auto seek file "rotates" with the log file but is not configurable.  With -S, the seek file is configurable but does not rotate.  What we really need is both.  I will work on this.

What we need is the ability to keep different, unique seek positions for a log file even using -m, right?  Would it help if I rework the -S option to take a string parameter that makes the seek file unique, even though its base filename is auto-generated (following the -m logic)?

Kind regads,
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
First of all I would like to say thank you for your time and your willingness to help me.
I think your idea could very well work!
Only one way to make sure :)
Thank you again.
Have a great week end.

p.s. I have recommended your plug-in to my colleague and I will do the same with other people who are in search of a great log check Nagios plug-in. Not only for its functionalities but for your support more than anything else. This is not the first time you have been quick on identify, suggest and resolve. Great Job!

**Comment by pmcaulay** [comment]
Hi,

Thanky you for your kind words.

I have changed the behaviour of -S so it now takes a string argument, which gets appended to generated seek filenames to make them unique.  Could you please pull the latest version (3.16) and give it a try?

Thanks,
Peter

**Comment by PitoneMaledetto** [comment]
Hi ,

```
./check_log3.pl --version
check_log3.pl version 3.15b
```

I believe is the 3.16(?) and maybe just my $plugin_revision = '3.15b'; needs updating...

We will test it and let you know thanks.

Regards

**Comment by pmcaulay** [comment]
Hi,

No, the version number is 3.16 but maybe there was a problem pushing it to github, could you please pull it again?

Thanks,
Peter

**Comment by PitoneMaledetto** [comment]
Hi Peter,
I can confirm that we were able to download 3.16.
I can also confirm that the -S option is working now as expected creating different seeks files for different services.
We will now check if we can set-up two different checks on the same log file with different seeks.
Thanks
Giuseppe

**Comment by smulitalo** [comment]
Hi Peter,
I am experiencing a similar issue with the check_logfiles reporting "critical -(1 errors) - cannot write status file /usr/lib/nagios/plugins/testconfig._usr_lib_nagios_plugins_status1.txt.alert1! check your filesystem (permissions / usage / integrity) and disk devices.

I am currently running check_logfiles version 4.1.1

I have granted full access permission to the directory and the seek file but it makes no difference. I have ran the command via command line and it gives the following output:

plugins# ./check_logfiles -t 60 -f /usr/lib/nagios/plugins/logfiles_config/testconfig2.cfg
OK - no errors or warnings|'es562ba_lines'=0 'es562ba_warnings'=0 'es562ba_criticals'=0 'es562ba_unknowns'=0 'es14d86_lines'=0 'es14d86_warnings'=0 'es14d86_criticals'=0 'es14d86_unknowns'=0 'if3_lines'=0 'if3_warnings'=0 'if3_criticals'=0 'if3_unknowns'=0

my config file is like this:
$seekfilesdir = '/usr/lib/nagios/plugins/logfiles_config';
$protocolsdir = '/usr/lib/nagios/plugins/';
$scriptpath = '/usr/lib/nagios/plugins';
@searches = (
  {
    tag => 'es562ba',
    logfile => '/usr/lib/nagios/plugins/status1.txt',
    criticalpatterns => 'isOnline: false',
    okpattern => [ 'isOnline: true' ],
   },

   {
     tag => 'es14d86',
     logfile => '/usr/lib/nagios/plugins/status1.txt',
     criticalpatterns => 'isOnline: false',
     okpattern => 'isOnline: true',
   },

  {
    tag => 'if3',
    logfile => '/usr/lib/nagios/plugins/status1.txt',
    criticalpatterns => 'isOnline: false',
    warningpatterns => [ 'TAG_CHANGES', 'TEMPERATURE_SENSOR_ERROR' ],
    okpattern => 'isOnline: true',
   },
);

my log file to be read is below:
{
  "code": "des-17-6-2022-562ba",
  "isOnline": true,
  "name": "BK Group DES 1",
  "type": "encodingStation",
  "location": null,
  "alerts": []
}
{
  "code": "des-29-6-2022-14d86",
  "isOnline": false,
  "name": "Replacement DES",
  "type": "encodingStation",
  "location": null,
  "alerts": []
}
{
  "code": "if-18-7-2022-d635c2",
  "isOnline": true,
  "name": "BK Group IF3",
  "type": "smartCabinet",
  "location": {
    "name": "Test BK World"
  },
  "alerts": [
    {
      "type": "TEMPERATURE_SENSOR_ERROR",
      "severity": 0.8,
      "lastTimeSeen": "2023-01-12T14:46:35.847Z",
      "description": "Temperature sensor connection has errors: Temperature sensor not found!"
    },
    {
      "type": "TAG_CHANGES",
      "severity": 0.8,
      "lastTimeSeen": "2023-01-12T00:32:49.993Z",
      "description": "Cabinet has 1 bad tags."
    }
  ]
}

Please let me know if anyone require more information.
Any help provided by anyone familiar with the issue within the community ismuch appreciated.

Kind regards,
Sonny

**Comment by pmcaulay** [comment]
Perhaps SELinux is preventing the nagios user from writing to /usr/lib/nagios/plugins ?
As check_logfiles is not one of mine I can't really help with this, sorry.

**Comment by smulitalo** [comment]
Hi Peter,
Thank you for getting back to me even though you're not able to help. I will continue to look for a solution. FYI, I have given the folder full access to everyone. I have tested the plugin via command line via user (non admin) I use to login to Debian server with same configuration options used with the plugin in Icinga2 and it works perfectly.

**Comment by smulitalo** [comment]
Here is the solution from Mr Laußer for my issue. I hope it will help someone else as it was exactly the solution for my issue and I also learned a very important lesson going forward. Thank you once again Mr Laußer for your prompt and astute diagnosis.

Hi Mister Mulitalo,
sorry for screaming, but:

plugins# ./check_logfiles -t 60 -f /usr/lib/nagios/plugins/logfiles_config/testconfig2.cfg

NEVER! NEVER! run a plugin on the command line as the root user!!!

 Whenever a plugin writes some status file, which it will read again when it runs next time, it will be owned by root. And then all kinds of trouble occur, as soon as the plugin is run under the user of the nagios process.

But as you write, that you changed permissions…..maybe there is some other reason.

Did you just change permissions or did you also change ownership?

But actually we should not follow this path at all. I see that you set the seekfilesdir to /usr/lib/…. which is a system path and where applications, especially dynamic and temporary files should absolutely not be located.

The default path is /var/tmp/check_logfiles, /var/tmp is the place of choice for all kind of temp and crap, like /tmp, but it will in any case be persistent after a reboot.

So just delete the $seekfilesdir (and let $protocolsdir also point to /tmp or /var/tmp) then the error should disappear.

Gerhard

**Comment by pmcaulay** [comment]
One addition to Gerhard's excellent remarks is that on a lot of distributions (RedHat and Debian based ones), the NRPE service runs with PrivateTmp=true, which can apparently prevent plugins from writing seek files to /tmp and /var/tmp.
