### ISSUE TITLE
check_log3.pl version 3.16 has not exit 2 in case of CRITICAL exit

### ISSUE THREAD

**Issue by emi65** [pmcaulay/nagios-plugins#16]
Hi expert
I using the check_log3.pl version 3.16
I did this command
/usr/lib/nagios/plugins/check_log3.pl -l logerr.log --show-filename -p ERROR --warning=1 --critical=1
CRITICAL: Found 1 lines (limit=1/1): [INFO] 2019-05-02 11:48:53,074 [MPHInst3] [v3.0.5.b] [CAMEL] [main] [n.d.m.s.r.i.MandatoryDataChecker] : {MPH-9900009} ERROR_OUTSC_INFO - Error outsourced mode [OFF] [sgsvrasipic03lx-mph.log]|lines=1
[nagios@sgsvrasnag006lx:/home/nag-script/SSHCheck/LogErrFile]$ echo $?
0

I found the serched error , I got CRITICAL in the output command but the exit code is 0 , so the nagios check stays in OK status

Why That ?

Thanks
Emilio

**Comment by pmcaulay** [comment]
Hi,

I'm afraid I cannot reproduce this behaviour. Can you please re-run the command with the --debug option?

Thanks,

--   
Peter Mc Aulay <pmcaulay@evilgeek.net>
GPG key ID: A0E108A9

**Comment by emi65** [comment]
I'm sorry 
It was a my error
I corretced it and now all works fine

thanks and sorry for the noise
Emilio

**Comment by pmcaulay** [comment]
Hi,

Ha, no problem!

Kind regards,
Peter
