### ISSUE TITLE
check_netapp-du.pl warning/critical logic is reversed

### ISSUE THREAD

**Issue by topinet** [pmcaulay/nagios-plugins#2]
When deployed check, I've realized that comparision are reversed, so help messages states that warning and critical parameters are values above them status is WARNING or CRITICAL:

Changes needed to correct this:

```
diff -Nr /usr/lib/nagios/custom-plugins/check_netapp-du.pl.orig /usr/lib/nagios/custom-plugins/check_netapp-du.pl
@@ -555,22 +564,22 @@
 	$status = "CRITICAL - VOLUME FULL";
 	$rc = $ERRORS{'CRITICAL'};
 # Disk space critical
-} elsif ($critical && $dfPctUsed < $critical) {
+} elsif ($critical && $dfPctUsed > $critical) {
 	$status = "CRITICAL";
 	$rc = $ERRORS{'CRITICAL'};
 
 # Disk space warning
-} elsif ($warning && $dfPctUsed < $warning) {
+} elsif ($warning && $dfPctUsed > $warning) {
 	$status = "WARNING";
 	$rc = $ERRORS{'WARNING'};
 
 # Files critical
-} elsif ($files_crit && $dfFilesUsed < $files_crit) {
+} elsif ($files_crit && $dfFilesUsed > $files_crit) {
 	$status = "FILES CRITICAL";
 	$rc = $ERRORS{'CRITICAL'};
 
 # Files warning
-} elsif ($files_warn && $dfFilesUsed < $files_warn) {
+} elsif ($files_warn && $dfFilesUsed > $files_warn) {
 	$status = "FILES WARNING";
 	$rc = $ERRORS{'WARNING'};

```

**Comment by pmcaulay** [comment]
Hi, 

Eek, you're right, of course.  I've corrected this. 

Thanks!

-- 
Peter Mc Aulay <pmcaulay@evilgeek.net>
GPG key ID: A0E108A9

On 2017-02-13 10:24, Toni Garcia-Navarro wrote:

> When deployed check, I've realized that comparision are reversed, so help messages states that warning and critical parameters are values above them status is WARNING or CRITICAL: 
> 
> Changes needed to correct this:
> 
> diff -Nr /usr/lib/nagios/custom-plugins/check_netapp-du.pl.orig /usr/lib/nagios/custom-plugins/check_netapp-du.pl
> @@ -555,22 +564,22 @@
> $status = "CRITICAL - VOLUME FULL";
> $rc = $ERRORS{'CRITICAL'};
> # Disk space critical
> -} elsif ($critical && $dfPctUsed < $critical) {
> +} elsif ($critical && $dfPctUsed > $critical) {
> $status = "CRITICAL";
> $rc = $ERRORS{'CRITICAL'};
> 
> # Disk space warning
> -} elsif ($warning && $dfPctUsed < $warning) {
> +} elsif ($warning && $dfPctUsed > $warning) {
> $status = "WARNING";
> $rc = $ERRORS{'WARNING'};
> 
> # Files critical
> -} elsif ($files_crit && $dfFilesUsed < $files_crit) {
> +} elsif ($files_crit && $dfFilesUsed > $files_crit) {
> $status = "FILES CRITICAL";
> $rc = $ERRORS{'CRITICAL'};
> 
> # Files warning
> -} elsif ($files_warn && $dfFilesUsed < $files_warn) {
> +} elsif ($files_warn && $dfFilesUsed > $files_warn) {
> $status = "FILES WARNING";
> $rc = $ERRORS{'WARNING'};
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pmcaulay/nagios-plugins","title":"pmcaulay/nagios-plugins","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pmcaulay/nagios-plugins"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"check_netapp-du.pl warning/critical logic is reversed (#2)"}],"action":{"name":"View Issue","url":"https://github.com/pmcaulay/nagios-plugins/issues/2"}}}
 

Links:
------
[1] https://github.com/pmcaulay/nagios-plugins/issues/2
[2]
