### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by mkiler** [pmcaulay/nagios-plugins#8]
Hello,
I have a problem to resolve, - i have a file and a pattern:
file

Enabled=0
Status=0
Amount1=34
Amount2=16
Amount3=28

And I have a pattern to search  when Amount(123) is smaller than 10
but if i do something like this  -p 'Amount1=3' -s /dev/null
they give me worning that they found line 

I would like to search value exactly    Amount1=3  but they search Amount1=34 or 35 or 378

Please tell me how to search exactly value?

**Comment by pmcaulay** [comment]
Hi,

You could go with the regular expression -p 'Amount[1-9]=3[^0-9]' where the ^ character basically means "not", but this is not very flexible.

Alternatively, you could get the plugin to actually do a numerical compare of the values.

Given an input file that contains this:

Enabled=0
Status=0
Amount1=34
Amount2=16
Amount3=28
Amount4=7
Amount5=3
Amount6=378

This will be the result:

$ ./check_log3.pl -l log -s /dev/null -p 'Amount[1-9]' -e '{ my @f=split(/=/); if ($f[1] < 10) { return 1 }}' -a
WARNING: Found 6 lines (limit=1/0): Parsed output (2 matched):
(1) Amount4=7
(2) Amount5=3|lines=6 parsed=2

Meaning, of the 6 lines found matching the regexp 'Amount[1-9]', there were two that also matched the condition of the value after the = sign being less than 10.  The thresholds will then apply to the result of the extra evaluation, not just the number of lines that match the -p expression.

This extra parsing ability is documented in the built-in manual (check_log3.pl --manual), with an example at the end.

Kind regards,
Peter
