### ISSUE TITLE
Matching pattern within log directory 

### ISSUE THREAD

**Issue by agit05** [pmcaulay/nagios-plugins#9]
Hi,

Great plugins, so just a quick question about the log3 check.
I am trying to filter all logs from /var/log/ diretory that matches any of the patterns:
'[Ee]rror', '[Ww]arning', '[Cc]ritical', '[Pp]roblem', '[Nn]o such'
And I am using the following command:
`./check_log3.pl --logfile=/var/log/ -m '*' -i -p '[Ee]rror' -p '[Ww]arning' -p '[Cc]ritical' -p '[Pp]roblem' -p '[Nn]o such' -t last_match`
Which returns me:
`OK: Found 0 lines (limit=1/0): No matches found.|lines=0`

While searching directly into a log file:
`/check_log3.pl --logfile=/var/log/messages -m '*' -i -p '[Ee]rror' -p '[Ww]arning' -p '[Cc]ritical' -p '[Pp]roblem' -p '[Nn]o such' -t last_match`
Will return me:
`WARNING: Found 667 lines (limit=1/0): Oct 15 03:29:17 hostname pcscd: 00000000 utils.c:53:GetDaemonPid() Can't open /var/run/pcscd/pcscd.pid: No such file or directory|lines=667
`

Any idea if this is a syntax error or a code error?
Thanks.

**Comment by sastorsl** [comment]
The plugin will use the pattern to select _one_ file. It won't do a wildcard search.

**Comment by agit05** [comment]
Any way to do a directory wildcard search, maybe in a feature release or some change I could implement in current version (no big fan of perl language :) ) ?

**Comment by agit05** [comment]
Anyhow, in the current version, if I want to search thru several files log files and folders from one command line, how should the syntax look like. I have tried:

`./check_log3.pl --logfile=/var/log/ -m '*/*log' -m '*log' -m 'messages' -m 'secure' -m 'spooler' -m 'dmesg' -m 'cron' -p 'error' -p 'warning' -p 'critical' -i -t last_match
`which always return:
`OK: Found 0 lines (limit=1/0): No matches found.|lines=0
`
While:
`./check_log3.pl --logfile=/var/log/ -m '*log' -m 'messages' -p 'warning' -i -t last_match
`Returns:
`WARNING: Found 5 lines (limit=1/0): Oct 17 18:00:09 hostname icinga2: [2017-10-17 18:00:09 +0200] warning/ApplyRule: `

**Comment by sastorsl** [comment]
Think you will need to write one command line for each file you want to match, and use patterns which does not overlap. There is an option for displaying which file is matched (just run the command without parameters to see the list) to help you with debugging.

**Comment by pmcaulay** [comment]
Indeed, the plugin is designed to check only one log file at a time.  The -m option just allows you to select among multiple log files.

You could write a small wrapper script to loop over the files you want to search, e.g.

```
STATE=0
for logfile in /var/log/*; do
    /usr/lib64/nagios/plugins/check_log3.pl --logfile=/var/log/$logfile -i -p '[Ee]rror' -p '[Ww]arning' -p '[Cc]ritical' -p '[Pp]roblem' -p '[Nn]o such' --show-filename --no-perfdata
    if [ $? -gt $STATE ]; then
        STATE=$?
    fi
done
exit $STATE
```

I hope that helps!
